### ISSUE TITLE
Code Coverage Generation

### ISSUE THREAD

**Issue by seanoshea** [material-foundation/material-scrollview-delegate-multiplexer-ios#10]
Opening an issue to deal with code coverage generation.

https://github.com/material-foundation/material-text-accessibility-ios/pull/7 has the details of where this was enabled for the `material-text-accessibility-ios` repo.

**Comment by chriscox** [comment]
This is awesome Sean. Looking into your pull request now.

**Comment by seanoshea** [comment]
@chriscox - no worries. Happy to help on this sort of stuff while I get my feet under me with some of the repos.

Difficult to know how best to up the code coverage for the repo for _just_ `UIScrollViewDelegate` methods when https://github.com/material-foundation/material-scrollview-delegate-multiplexer-ios/issues/3 is in the works too. Kinda feel like some kind of generic solution for unit testing would be best rather than _just_ focusing on `UIScrollViewDelegate` methods.
