### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by seanoshea** [material-foundation/material-scrollview-delegate-multiplexer-ios#6]
Was checking out the repo and ran across this _insanely_ minor typo.

```
  // Lets return the results from the oberserver which is equal to self.
  if (respondingObservers[0] == self) {
    return [results pointerAtIndex:0];
  }
```

Unsure of whether you accept PRs like this, but thought I'd at least offer up a PR.

**Comment by jverkoey** [comment]
Thanks for filing! We do accept pull requests :)

Please check out our [CONTRIBUTING.md](https://github.com/material-foundation/MDFScrollViewDelegateMultiplexer/blob/develop/CONTRIBUTING.md) document, specifically the heading on "Before you contribute". You'll need to sign Google's CLA before we can merge the pull request in.

**Comment by seanoshea** [comment]
@jverkoey Fantastic stuff. I've signed the CLA and opened up https://github.com/material-foundation/MDFScrollViewDelegateMultiplexer/pull/7.

**Comment by chriscox** [comment]
Thanks for the fix.

**Comment by seanoshea** [comment]
@chriscox - you're more than welcome.
